// <auto-generated />
namespace pys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CretateTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CretateTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202301232125116_CretateTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
